Add ROLE_MANAGER, ROLE_TEACHER, ROLE_STUDENT
phktn/on-premises-e-learning pull request #1
Opened 2020-12-05 08:01 UTC by mizo0203

下記 3 つの権限を追加

* `ROLE_MANAGER` : (生徒の) 管理者、上司
* `ROLE_TEACHER` : 講師
* `ROLE_STUDENT` : 生徒

2020-12-05 12:01 UTC, hayatedayon requested changes
Webページのtemplateの修正をお願いします

2020-12-05 12:01 UTC, hayatedayon commented on src/main/resources/templates/members/manager/index.html
> +    <title>Admin Role Contents</title>
Managerです

2020-12-05 12:01 UTC, hayatedayon commented on src/main/resources/templates/members/manager/index.html
> +            <div class="large">ADMINロールを付与されたユーザーだけがアクセスできるコンテンツページ</div>
Managerです

2020-12-05 12:01 UTC, hayatedayon commented on src/main/resources/templates/members/student/index.html
> +    <title>Admin Role Contents</title>
Studentです

2020-12-05 12:01 UTC, hayatedayon commented on src/main/resources/templates/members/student/index.html
> +            <div class="large">ADMINロールを付与されたユーザーだけがアクセスできるコンテンツページ</div>
Studentです

2020-12-05 12:01 UTC, hayatedayon commented on src/main/resources/templates/members/teacher/index.html
> +    <title>Admin Role Contents</title>
Teacherです

2020-12-05 12:01 UTC, hayatedayon commented on src/main/resources/templates/members/teacher/index.html
> +            <div class="large">ADMINロールを付与されたユーザーだけがアクセスできるコンテンツページ</div>
Teacherです

2021-01-09 02:41 UTC, mizo0203 commented
> Webページのtemplateの修正をお願いします

修正しました！

2021-01-09 04:36 UTC, merged